apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: fortune-teller
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: fortune-teller
  minReplicas: 1
  maxReplicas: 6
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50
